apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-secret
  template:
    metadata:
      labels:
        app: nodejs-secret
    spec:
      containers:
      - name: nodejs-secret
        image: shay88/k8s-node-app:secret
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-with-secret