# Use the official Node.js 16 image as a parent image
FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package.json ./
COPY package-lock.json* ./

# Install dependencies
RUN npm install

# Bundle your app source inside the Docker image
COPY . .

# Make your app available on port 3000
EXPOSE 3000

# Define the command to run your app
CMD [ "node", "index.js" ]